stages:
- build
- publish

linux:
    stage: build
    tags:
    - docker
    image: 7hazard/node-clang-7
    
    script:
    # build
    - "cd capi && ./build.sh && cd .."
    
    # server packaging
    - "mkdir capi/BUILD/altv-capi-server/include"
    - "mkdir capi/BUILD/altv-capi-server/include/server"
    - "cp capi/server/altv-capi.h capi/BUILD/altv-capi-server/include/server/altv-capi.h"
    - "cp capi/server/altv-capi.hpp capi/BUILD/altv-capi-server/include/server/altv-capi.hpp"
    - "cp capi/altv-capi-extra.h capi/BUILD/altv-capi-server/include/altv-capi-extra.h"
    - "cp capi/server/altv-capi.json capi/BUILD/altv-capi-server/altv-capi.json"
    - "cd capi/BUILD && zip -r altv-capi-server-linux.zip altv-capi-server && cd ../../"
    
    # client packaging
    - "mkdir capi/BUILD/altv-capi-client/include"
    - "mkdir capi/BUILD/altv-capi-client/include/client"
    - "cp capi/client/altv-capi.h capi/BUILD/altv-capi-client/include/client/altv-capi.h"
    - "cp capi/client/altv-capi.hpp capi/BUILD/altv-capi-client/include/client/altv-capi.hpp"
    - "cp capi/altv-capi-extra.h capi/BUILD/altv-capi-client/include/altv-capi-extra.h"
    - "cp capi/client/altv-capi.json capi/BUILD/altv-capi-client/altv-capi.json"
    - "cd capi/BUILD && zip -r altv-capi-client-linux.zip altv-capi-client && cd ../../"
    
    artifacts:
        name: "altv-capi-linux-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}"
        paths:
        - capi/BUILD/altv-capi-server-linux.zip
        - capi/BUILD/altv-capi-client-linux.zip
    
    variables:
        GIT_SUBMODULE_STRATEGY: recursive

win32:
    stage: build
    tags:
    - docker
    image: 7hazard/node-clang-win32-cross
    
    script:
    # build
    - "cd capi && ./build-win32.sh && cd .."
    
    # server packaging
    - "mkdir capi/BUILD-WIN32/altv-capi-server/include"
    - "mkdir capi/BUILD-WIN32/altv-capi-server/include/server"
    - "cp capi/server/altv-capi.h capi/BUILD-WIN32/altv-capi-server/include/server/altv-capi.h"
    - "cp capi/server/altv-capi.hpp capi/BUILD-WIN32/altv-capi-server/include/server/altv-capi.hpp"
    - "cp capi/altv-capi-extra.h capi/BUILD-WIN32/altv-capi-server/include/altv-capi-extra.h"
    - "cp capi/server/altv-capi.json capi/BUILD-WIN32/altv-capi-server/altv-capi.json"
    - "cd capi/BUILD-WIN32 && zip -r altv-capi-server-win32.zip altv-capi-server && cd ../../"
    
    # client packaging
    - "mkdir capi/BUILD-WIN32/altv-capi-client/include"
    - "mkdir capi/BUILD-WIN32/altv-capi-client/include/client"
    - "cp capi/client/altv-capi.h capi/BUILD-WIN32/altv-capi-client/include/client/altv-capi.h"
    - "cp capi/client/altv-capi.hpp capi/BUILD-WIN32/altv-capi-client/include/client/altv-capi.hpp"
    - "cp capi/altv-capi-extra.h capi/BUILD-WIN32/altv-capi-client/include/altv-capi-extra.h"
    - "cp capi/client/altv-capi.json capi/BUILD-WIN32/altv-capi-client/altv-capi.json"
    - "cd capi/BUILD-WIN32 && zip -r altv-capi-client-win32.zip altv-capi-client && cd ../../"
    
    artifacts:
        name: "altv-capi-win32-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}"
        paths:
        - capi/BUILD-WIN32/altv-capi-server-win32.zip
        - capi/BUILD-WIN32/altv-capi-client-win32.zip
    
    variables:
        GIT_SUBMODULE_STRATEGY: recursive

publish-binaries:
    stage: publish
    tags:
    - linux
    
    script:
    - "curl --header 'Content-Type: application/json' --header 'PRIVATE-TOKEN: ${CI_GITLAB_API_PRIVATE_KEY}' \
     --data '{ \"name\": \"Build ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\", \"tag_name\": \"${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\", \"description\": \"Build for ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\", \"milestones\": [\"v0\"], \"assets\": { \"links\": [\
        { \"name\": \"client-win32\", \"url\": \"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD-WIN32/altv-capi-client-win32.zip?inline=false\" }\
        { \"name\": \"server-win32\", \"url\": \"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD-WIN32/altv-capi-server-win32.zip?inline=false\" }\
        { \"name\": \"client-linux\", \"url\": \"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD/altv-capi-client.zip?inline=false\" }\
        { \"name\": \"server-linux\", \"url\": \"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD/altv-capi-server.zip?inline=false\" }\
     ] } }' \
     --request POST https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases"
