# stages:
# - build
# - publish

build-and-publish:
    # stage: build
    tags:
        - docker
    image: 7hazard/node-clang-win32-cross
    
    script:
        - "echo Build ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID} '|' Project ID ${CI_PROJECT_ID} '|' Job ID ${CI_JOB_ID} '|' API Key ${CI_GITLAB_API_PRIVATE_KEY}" 
        
        ## WIN32
        # build
        - "cd capi && ./build-win32.sh && cd .."
        
        # client packaging
        - "mkdir capi/BUILD-WIN32/altv-capi-client/include"
        - "mkdir capi/BUILD-WIN32/altv-capi-client/include/client"
        - "cp capi/client/altv-capi.h capi/BUILD-WIN32/altv-capi-client/include/client/altv-capi.h"
        - "cp capi/client/altv-capi.hpp capi/BUILD-WIN32/altv-capi-client/include/client/altv-capi.hpp"
        - "cp capi/altv-capi-extra.h capi/BUILD-WIN32/altv-capi-client/include/altv-capi-extra.h"
        - "cp capi/client/altv-capi.json capi/BUILD-WIN32/altv-capi-client/altv-capi.json"
        - "cd capi/BUILD-WIN32 && zip -r altv-capi-client-win32.zip altv-capi-client && cd ../../"
        
        # client-static packaging
        - "mkdir capi/BUILD-WIN32/altv-capi-client-static/include"
        - "mkdir capi/BUILD-WIN32/altv-capi-client-static/include/client"
        - "cp capi/client/altv-capi.h capi/BUILD-WIN32/altv-capi-client-static/include/client/altv-capi.h"
        - "cp capi/client/altv-capi.hpp capi/BUILD-WIN32/altv-capi-client-static/include/client/altv-capi.hpp"
        - "cp capi/altv-capi-extra.h capi/BUILD-WIN32/altv-capi-client-static/include/altv-capi-extra.h"
        - "cp capi/client/altv-capi.json capi/BUILD-WIN32/altv-capi-client-static/altv-capi.json"
        - "cd capi/BUILD-WIN32 && zip -r altv-capi-client-static-win32.zip altv-capi-client-static && cd ../../"
        
        # server packaging
        - "mkdir capi/BUILD-WIN32/altv-capi-server/include"
        - "mkdir capi/BUILD-WIN32/altv-capi-server/include/server"
        - "cp capi/server/altv-capi.h capi/BUILD-WIN32/altv-capi-server/include/server/altv-capi.h"
        - "cp capi/server/altv-capi.hpp capi/BUILD-WIN32/altv-capi-server/include/server/altv-capi.hpp"
        - "cp capi/altv-capi-extra.h capi/BUILD-WIN32/altv-capi-server/include/altv-capi-extra.h"
        - "cp capi/server/altv-capi.json capi/BUILD-WIN32/altv-capi-server/altv-capi.json"
        - "cd capi/BUILD-WIN32 && zip -r altv-capi-server-win32.zip altv-capi-server && cd ../../"
        
        # server-static packaging
        - "mkdir capi/BUILD-WIN32/altv-capi-server-static/include"
        - "mkdir capi/BUILD-WIN32/altv-capi-server-static/include/server"
        - "cp capi/server/altv-capi.h capi/BUILD-WIN32/altv-capi-server-static/include/server/altv-capi.h"
        - "cp capi/server/altv-capi.hpp capi/BUILD-WIN32/altv-capi-server-static/include/server/altv-capi.hpp"
        - "cp capi/altv-capi-extra.h capi/BUILD-WIN32/altv-capi-server-static/include/altv-capi-extra.h"
        - "cp capi/server/altv-capi.json capi/BUILD-WIN32/altv-capi-server-static/altv-capi.json"
        - "cd capi/BUILD-WIN32 && zip -r altv-capi-server-static-win32.zip altv-capi-server-static && cd ../../"

        ## LINUX
        # build
        - "cd capi && ./build.sh && cd .."
        
        # # client packaging
        # - "mkdir capi/BUILD/altv-capi-client/include"
        # - "mkdir capi/BUILD/altv-capi-client/include/client"
        # - "cp capi/client/altv-capi.h capi/BUILD/altv-capi-client/include/client/altv-capi.h"
        # - "cp capi/client/altv-capi.hpp capi/BUILD/altv-capi-client/include/client/altv-capi.hpp"
        # - "cp capi/altv-capi-extra.h capi/BUILD/altv-capi-client/include/altv-capi-extra.h"
        # - "cp capi/client/altv-capi.json capi/BUILD/altv-capi-client/altv-capi.json"
        # - "cd capi/BUILD && zip -r altv-capi-client-linux.zip altv-capi-client && cd ../../"
        
        # # client-static packaging
        # - "mkdir capi/BUILD/altv-capi-client-static/include"
        # - "mkdir capi/BUILD/altv-capi-client-static/include/client"
        # - "cp capi/client/altv-capi.h capi/BUILD/altv-capi-client-static/include/client/altv-capi.h"
        # - "cp capi/client/altv-capi.hpp capi/BUILD/altv-capi-client-static/include/client/altv-capi.hpp"
        # - "cp capi/altv-capi-extra.h capi/BUILD/altv-capi-client-static/include/altv-capi-extra.h"
        # - "cp capi/client/altv-capi.json capi/BUILD/altv-capi-client-static/altv-capi.json"
        # - "cd capi/BUILD && zip -r altv-capi-client-static-linux.zip altv-capi-client-static && cd ../../"
        
        # server packaging
        - "mkdir capi/BUILD/altv-capi-server/include"
        - "mkdir capi/BUILD/altv-capi-server/include/server"
        - "cp capi/server/altv-capi.h capi/BUILD/altv-capi-server/include/server/altv-capi.h"
        - "cp capi/server/altv-capi.hpp capi/BUILD/altv-capi-server/include/server/altv-capi.hpp"
        - "cp capi/altv-capi-extra.h capi/BUILD/altv-capi-server/include/altv-capi-extra.h"
        - "cp capi/server/altv-capi.json capi/BUILD/altv-capi-server/altv-capi.json"
        - "cd capi/BUILD && zip -r altv-capi-server-linux.zip altv-capi-server && cd ../../"
        
        # server-static packaging
        - "mkdir capi/BUILD/altv-capi-server-static/include"
        - "mkdir capi/BUILD/altv-capi-server-static/include/server"
        - "cp capi/server/altv-capi.h capi/BUILD/altv-capi-server-static/include/server/altv-capi.h"
        - "cp capi/server/altv-capi.hpp capi/BUILD/altv-capi-server-static/include/server/altv-capi.hpp"
        - "cp capi/altv-capi-extra.h capi/BUILD/altv-capi-server-static/include/altv-capi-extra.h"
        - "cp capi/server/altv-capi.json capi/BUILD/altv-capi-server-static/altv-capi.json"
        - "cd capi/BUILD && zip -r altv-capi-server-static-linux.zip altv-capi-server-static && cd ../../"

        ## PUBLISH
        - "echo TESTING ENV VARS: $CI_TEST_VAL '|' $CI_TEST_VAL_MASKED '|' ${CI_TEST_VAL} '|' ${CI_TEST_VAL_MASKED}"
        - "echo PUBLISHING"
        - "echo Build ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID} '|' Project ID ${CI_PROJECT_ID} '|' Job ID ${CI_JOB_ID} '|' API Key ${CI_GITLAB_API_PRIVATE_KEY}" 
        
        # linux client builds, if there ever is a chance for that to be needed
        # { \\\"name\\\": \\\"client-linux\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD/altv-capi-client-linux.zip?inline=false\\\" },
        # { \\\"name\\\": \\\"client-linux\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD/altv-capi-client-static-linux.zip?inline=false\\\" },
        - "curl --header \"Content-Type: application/json\" --header \"PRIVATE-TOKEN: ${CI_GITLAB_API_PRIVATE_KEY}\" 
        --data \"{ \\\"name\\\": \\\"${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\\\", \\\"tag_name\\\": \\\"${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\\\", \\\"ref\\\": \\\"${CI_COMMIT_REF_SLUG}\\\", \\\"description\\\": \\\"Build ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\\\", \\\"assets\\\": { \\\"links\\\": [
            { \\\"name\\\": \\\"client-win32\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD-WIN32/altv-capi-client-win32.zip?inline=false\\\" },
            { \\\"name\\\": \\\"client-win32\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD-WIN32/altv-capi-client-static-win32.zip?inline=false\\\" },
            { \\\"name\\\": \\\"server-win32\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD-WIN32/altv-capi-server-win32.zip?inline=false\\\" },
            { \\\"name\\\": \\\"server-win32\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD-WIN32/altv-capi-server-static-win32.zip?inline=false\\\" },
            { \\\"name\\\": \\\"server-linux\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD/altv-capi-server.zip?inline=false\\\" },
            { \\\"name\\\": \\\"server-linux\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD/altv-capi-server-static-linux.zip?inline=false\\\" }
        ]} }\"
        --request POST https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases"
    
    artifacts:
        name: "altv-capi-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}"
        paths:
            - capi/BUILD-WIN32/altv-capi-client-win32.zip
            - capi/BUILD-WIN32/altv-capi-client-static-win32.zip
            - capi/BUILD-WIN32/altv-capi-server-win32.zip
            - capi/BUILD-WIN32/altv-capi-server-static-win32.zip
            # - capi/BUILD/altv-capi-client-linux.zip
            # - capi/BUILD/altv-capi-client-static-linux.zip
            - capi/BUILD/altv-capi-server-linux.zip
            - capi/BUILD/altv-capi-server-static-linux.zip
    
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    
    only:
        refs:
            - master
        # variables:
        #     - $CI_COMMIT_REF_PROTECTED # only protected branches



# linux:
#     stage: build
#     tags:
#     - docker
#     image: 7hazard/node-clang-7
    
#     script:
#     # build
#     - "cd capi && ./build.sh && cd .."
    
#     # server packaging
#     - "mkdir capi/BUILD/altv-capi-server/include"
#     - "mkdir capi/BUILD/altv-capi-server/include/server"
#     - "cp capi/server/altv-capi.h capi/BUILD/altv-capi-server/include/server/altv-capi.h"
#     - "cp capi/server/altv-capi.hpp capi/BUILD/altv-capi-server/include/server/altv-capi.hpp"
#     - "cp capi/altv-capi-extra.h capi/BUILD/altv-capi-server/include/altv-capi-extra.h"
#     - "cp capi/server/altv-capi.json capi/BUILD/altv-capi-server/altv-capi.json"
#     - "cd capi/BUILD && zip -r altv-capi-server-linux.zip altv-capi-server && cd ../../"
    
#     # client packaging
#     - "mkdir capi/BUILD/altv-capi-client/include"
#     - "mkdir capi/BUILD/altv-capi-client/include/client"
#     - "cp capi/client/altv-capi.h capi/BUILD/altv-capi-client/include/client/altv-capi.h"
#     - "cp capi/client/altv-capi.hpp capi/BUILD/altv-capi-client/include/client/altv-capi.hpp"
#     - "cp capi/altv-capi-extra.h capi/BUILD/altv-capi-client/include/altv-capi-extra.h"
#     - "cp capi/client/altv-capi.json capi/BUILD/altv-capi-client/altv-capi.json"
#     - "cd capi/BUILD && zip -r altv-capi-client-linux.zip altv-capi-client && cd ../../"
    
#     artifacts:
#         name: "altv-capi-linux-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}"
#         paths:
#         - capi/BUILD/altv-capi-server-linux.zip
#         - capi/BUILD/altv-capi-client-linux.zip
    
#     variables:
#         GIT_SUBMODULE_STRATEGY: recursive

# win32:
#     stage: build
#     tags:
#     - docker
#     image: 7hazard/node-clang-win32-cross
    
#     script:
#     # build
#     - "cd capi && ./build-win32.sh && cd .."
    
#     # server packaging
#     - "mkdir capi/BUILD-WIN32/altv-capi-server/include"
#     - "mkdir capi/BUILD-WIN32/altv-capi-server/include/server"
#     - "cp capi/server/altv-capi.h capi/BUILD-WIN32/altv-capi-server/include/server/altv-capi.h"
#     - "cp capi/server/altv-capi.hpp capi/BUILD-WIN32/altv-capi-server/include/server/altv-capi.hpp"
#     - "cp capi/altv-capi-extra.h capi/BUILD-WIN32/altv-capi-server/include/altv-capi-extra.h"
#     - "cp capi/server/altv-capi.json capi/BUILD-WIN32/altv-capi-server/altv-capi.json"
#     - "cd capi/BUILD-WIN32 && zip -r altv-capi-server-win32.zip altv-capi-server && cd ../../"
    
#     # client packaging
#     - "mkdir capi/BUILD-WIN32/altv-capi-client/include"
#     - "mkdir capi/BUILD-WIN32/altv-capi-client/include/client"
#     - "cp capi/client/altv-capi.h capi/BUILD-WIN32/altv-capi-client/include/client/altv-capi.h"
#     - "cp capi/client/altv-capi.hpp capi/BUILD-WIN32/altv-capi-client/include/client/altv-capi.hpp"
#     - "cp capi/altv-capi-extra.h capi/BUILD-WIN32/altv-capi-client/include/altv-capi-extra.h"
#     - "cp capi/client/altv-capi.json capi/BUILD-WIN32/altv-capi-client/altv-capi.json"
#     - "cd capi/BUILD-WIN32 && zip -r altv-capi-client-win32.zip altv-capi-client && cd ../../"
    
#     artifacts:
#         name: "altv-capi-win32-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}"
#         paths:
#         - capi/BUILD-WIN32/altv-capi-server-win32.zip
#         - capi/BUILD-WIN32/altv-capi-client-win32.zip
    
#     variables:
#         GIT_SUBMODULE_STRATEGY: recursive

# publish-binaries:
#     stage: publish
#     tags:
#     - linux
    
#     script:
#     - "echo TESTING ENV VARS: $CI_TEST_VAL '|' $CI_TEST_VAL_MASKED '|' ${CI_TEST_VAL} '|' ${CI_TEST_VAL_MASKED}"
#     - "let LINUX_JOB_ID=${CI_JOB_ID}-2"
#     - "let WIN32_JOB_ID=${CI_JOB_ID}-1"
#     - "echo Build ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID} '|' Project ID ${CI_PROJECT_ID} '|' Linux Job ID $LINUX_JOB_ID '|' Win32 Job ID $WI32_JOB_ID"
#     - 'CURL_DATA="{ \"name\": \"${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\", \"tag_name\": \"${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\", \"ref\": \"${CI_COMMIT_REF_SLUG}\", \"description\": \"Build ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\", \"assets\": { \"links\": [
#         { \"name\": \"client-win32\", \"url\": \"https://gitlab.com/7Hazard/altv-capi/-/jobs/$WIN32_JOB_ID/artifacts/raw/capi/BUILD-WIN32/altv-capi-client-win32.zip?inline=false\" }
#         { \"name\": \"server-win32\", \"url\": \"https://gitlab.com/7Hazard/altv-capi/-/jobs/$WIN32_JOB_ID/artifacts/raw/capi/BUILD-WIN32/altv-capi-server-win32.zip?inline=false\" }
#         { \"name\": \"client-linux\", \"url\": \"https://gitlab.com/7Hazard/altv-capi/-/jobs/$LINUX_JOB_ID/artifacts/raw/capi/BUILD/altv-capi-client.zip?inline=false\" }
#         { \"name\": \"server-linux\", \"url\": \"https://gitlab.com/7Hazard/altv-capi/-/jobs/$LINUX_JOB_ID/artifacts/raw/capi/BUILD/altv-capi-server.zip?inline=false\" }
#      ] } }"'
#     - "curl --header 'Content-Type: application/json' --header \"PRIVATE-TOKEN: $CI_GITLAB_API_PRIVATE_KEY\" 
#      --data \"$CURL_DATA\"
#      --request POST https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases"
